/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package htlwrn.swingairlines;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author elvin
 */
public class WorldMap extends javax.swing.JPanel {

    /**
     * Creates new form WorldMap
     */
    public WorldMap() {
        initComponents();
    }
    
    public void setMain(Main obj) {
        this.obj = obj;
    }
    
    public void setPicture() {
        try {
            img = ImageIO.read(new File("Earthmap.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(WorldMap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2 = (Graphics2D) g;
        int w = this.getWidth();
        int h = this.getHeight();
        g2.drawImage(img, 0, 0, w, h, 0, 0, img.getWidth(), img.getHeight(), null);
        drawInPicture(g);
    }
    
    public void drawInPicture(Graphics g) {
        
        if(listExists()) {
            
            int[][] coordinates = new int[routeList.size()][2];
            for(int i = 0; i < routeList.size(); i++) {
                
                g.setColor(Color.red);

                int posX = (int)(obj.getAirportFromIata(routeList.get(i)).getLongitude() + 180) * this.getWidth() / 360; // -5 -> Punkt soll in der Mitte vom Kreis sein, Kreislänge 10
                int posY = (int)(90 - obj.getAirportFromIata(routeList.get(i)).getLatitude()) * this.getHeight() / 180;
                
                coordinates[i][0] = posX;
                coordinates[i][1] = posY;
                
                g.drawOval(posX -  5, posY - 5, 10, 10);
               
                g.setColor(Color.white);
                g.drawChars(obj.getAirportFromIata(routeList.get(i)).getIata().toCharArray(), 0, start.getIata().toCharArray().length
                    , posX + 10, posY - 3);
                
            }
            
            for(int i = 1; i < coordinates.length; i++) {
                g.drawLine(coordinates[i - 1][0], coordinates[i - 1][1], coordinates[i][0], coordinates[i][1]);
            }
        }
    }
    
    private boolean listExists() {
        if(routeList == null) return false;
        
        for(String iata : routeList) {
            if(iata == null) return false;
        }
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public BufferedImage img; 
    public Airport start, end;
    public List<String> routeList;
    public Main obj;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
